import PointModel from './model/point_model.js';
import Presenter from './presenter/presenter.js';
import HeaderPresenter from './presenter/header-presenter.js';
const siteMainElement = document.querySelector('.trip-events');
const headerContainer = document.querySelector('.trip-main');
const pointModel = new PointModel();
pointModel.init();
const presenter = new Presenter({container: siteMainElement, pointModel});
presenter.init();
const HeaderPresenters = new HeaderPresenter({headerContainer: headerContainer, pointModel});
HeaderPresenters.init();
